import { InputFileWithSize } from './buildTreeData';

const exampleData: InputFileWithSize[] = [
  { fullPath: 'src/scenario/graph/RepaymentsGraph.tsx', size: 36 },
  { fullPath: 'src/math/__tests__/calculateLoanPeriods.test.tsx', size: 97 },
  { fullPath: 'src/App.tsx', size: 97 },
  { fullPath: 'src/scenario/ScenarioInputs.tsx', size: 92 },
  { fullPath: 'src/scenario/graph/RepaymentColumn.tsx', size: 92 },
  { fullPath: 'src/scenario/RepaymentsStats.tsx', size: 80 },
  {
    fullPath: 'src/scenario/graph/__tests__/RepaymentsGraph.test.tsx',
    size: 80,
  },
  { fullPath: 'src/scenario/ScenarioPanel.tsx', size: 78 },
  { fullPath: 'src/scenario/__tests__/ScenarioInputs.test.tsx', size: 71 },
  { fullPath: 'src/math/__tests__/LoanPeriod.test.tsx', size: 71 },
  { fullPath: 'src/styles/index.css', size: 66 },
  { fullPath: 'src/scenario/__tests__/RepaymentsStats.test.tsx', size: 65 },
  { fullPath: 'src/__tests__/StateStorage.test.tsx', size: 65 },
  { fullPath: 'src/scenario/graph/GridLines.tsx', size: 62 },
  { fullPath: 'src/math/calculateLoanPeriods.tsx', size: 62 },
  { fullPath: 'src/scenario/__tests__/ScenarioPanel.test.tsx', size: 61 },
  { fullPath: 'src/__tests__/App.test.tsx', size: 60 },
  { fullPath: 'src/scenario/graph/HoverBox.tsx', size: 55 },
  { fullPath: 'src/header/HeaderMenu.tsx', size: 53 },
  { fullPath: 'package.json', size: 51 },
  { fullPath: 'src/math/LoanPeriod.tsx', size: 50 },
  {
    fullPath: 'src/scenario/graph/__tests__/RepaymentColumn.test.tsx',
    size: 49,
  },
  { fullPath: 'src/scenario/graph/__tests__/GridLines.test.tsx', size: 49 },
  { fullPath: 'src/scenario/graph/__tests__/HoverBox.test.tsx', size: 48 },
  { fullPath: 'src/scenario/ScenarioFieldSelector.tsx', size: 42 },
  { fullPath: 'src/header/HeaderForm.tsx', size: 40 },
  { fullPath: 'src/form/Inputs.tsx', size: 38 },
  { fullPath: 'src/StateStorage.ts', size: 34 },
  { fullPath: 'src/scenario/graph/OffsetTrendLineSegment.tsx', size: 33 },
  { fullPath: 'src/__tests__/formatting.test.tsx', size: 32 },
  {
    fullPath: 'src/scenario/graph/__tests__/getGridLineInterval.test.tsx',
    size: 29,
  },
  { fullPath: 'src/icons/CrossInSquare.tsx', size: 28 },
  { fullPath: 'src/icons/PlusInCircle.tsx', size: 27 },
  { fullPath: 'src/setupTests.ts', size: 27 },
  { fullPath: 'src/icons/Hamburger.tsx', size: 26 },
  { fullPath: 'src/form/__tests__/Inputs.test.tsx', size: 25 },
  { fullPath: 'src/scenario/graph/getGridLineInterval.tsx', size: 24 },
  { fullPath: 'src/scenario/ScenarioHeader.tsx', size: 23 },
  { fullPath: 'tsconfig.json', size: 21 },
  { fullPath: 'src/models.ts', size: 21 },
  { fullPath: 'src/formatting.tsx', size: 19 },
  { fullPath: 'src/icons/CrossInCircle.tsx', size: 18 },
  { fullPath: 'src/header/Header.tsx', size: 16 },
  { fullPath: 'src/modals/Modal.tsx', size: 16 },
  { fullPath: 'src/AddScenarioButton.tsx', size: 15 },
  { fullPath: 'tailwind.config.js', size: 13 },
  { fullPath: 'src/scenario/Table.tsx', size: 12 },
  { fullPath: 'README.md', size: 12 },
  { fullPath: 'public/index.html', size: 12 },
  { fullPath: 'postcss.config.js', size: 11 },
  { fullPath: 'src/math/calculateRepayment.ts', size: 7 },
  { fullPath: 'src/index.tsx', size: 5 },
  { fullPath: 'src/react-app-env.d.ts', size: 0 },
];

export default exampleData;
